export const craftingInfusionTreasureClass = {
  'Treasure Class': 'CraftingInfusion',
  group: '',
  level: '',
  Picks: '1',
  Unique: '',
  Set: '',
  Rare: '',
  Magic: '',
  NoDrop: '',
  Item1: 'crfb',
  Prob1: '1',
  Item2: 'crfc',
  Prob2: '1',
  Item3: 'crfs',
  Prob3: '1',
  Item4: 'crfh',
  Prob4: '1',
  Item5: 'crfv',
  Prob5: '1',
  Item6: 'crfu',
  Prob6: '1',
  Item7: 'crfp',
  Prob7: '1',
  Item8: '',
  Prob8: '',
  Item9: '',
  Prob9: '',
  Item10: '',
  Prob10: '',
  SumItems: '',
  TotalProb: '',
  DropChance: '',
  'Term': '0'
}

export const facetCraftingRecipe = {
  description: 'Facet',
  enabled: '1',
  ladder: '',
  'min diff': '',
  version: '100',
  op: '',
  param: '',
  value: '',
  class: '',
  numinputs: '3',
  'input 1': '"isc,qty=1"',
  'input 2': '"tsc,qty=1"',
  'input 3': '"jewf,qty=10"',
  'input 4': '',
  'input 5': '',
  'input 6': '',
  'input 7': '',
  output: '"jew,uni"',
  lvl: '85',
  plvl: '',
  ilvl: '85',
  'mod 1': '',
  'mod 1 chance': '',
  'mod 1 param': '',
  'mod 1 min': '',
  'mod 1 max': '',
  'mod 2': '',
  'mod 2 chance': '',
  'mod 2 param': '',
  'mod 2 min': '',
  'mod 2 max': '',
  'mod 3': '',
  'mod 3 chance': '',
  'mod 3 param': '',
  'mod 3 min': '',
  'mod 3 max': '',
  'mod 4': '',
  'mod 4 chance': '',
  'mod 4 param': '',
  'mod 4 min': '',
  'mod 4 max': '',
  'mod 5': '',
  'mod 5 chance': '',
  'mod 5 param': '',
  'mod 5 min': '',
  'mod 5 max': '',
  'output b': '',
  'b lvl': '',
  'b plvl': '',
  'b ilvl': '',
  'b mod 1': '',
  'b mod 1 chance': '',
  'b mod 1 param': '',
  'b mod 1 min': '',
  'b mod 1 max': '',
  'b mod 2': '',
  'b mod 2 chance': '',
  'b mod 2 param': '',
  'b mod 2 min': '',
  'b mod 2 max': '',
  'b mod 3': '',
  'b mod 3 chance': '',
  'b mod 3 param': '',
  'b mod 3 min': '',
  'b mod 3 max': '',
  'b mod 4': '',
  'b mod 4 chance': '',
  'b mod 4 param': '',
  'b mod 4 min': '',
  'b mod 4 max': '',
  'b mod 5': '',
  'b mod 5 chance': '',
  'b mod 5 param': '',
  'b mod 5 min': '',
  'b mod 5 max': '',
  'output c': '',
  'c lvl': '',
  'c plvl': '',
  'c ilvl': '',
  'c mod 1': '',
  'c mod 1 chance': '',
  'c mod 1 param': '',
  'c mod 1 min': '',
  'c mod 1 max': '',
  'c mod 2': '',
  'c mod 2 chance': '',
  'c mod 2 param': '',
  'c mod 2 min': '',
  'c mod 2 max': '',
  'c mod 3': '',
  'c mod 3 chance': '',
  'c mod 3 param': '',
  'c mod 3 min': '',
  'c mod 3 max': '',
  'c mod 4': '',
  'c mod 4 chance': '',
  'c mod 4 param': '',
  'c mod 4 min': '',
  'c mod 4 max': '',
  'c mod 5': '',
  'c mod 5 chance': '',
  'c mod 5 param': '',
  'c mod 5 min': '',
  'c mod 5 max': '',
  '*eol': '0'
}