export const craftingInfusionTreasureClass = {
  'Treasure Class': 'CraftingInfusion',
  group: '',
  level: '',
  Picks: '1',
  Unique: '',
  Set: '',
  Rare: '',
  Magic: '',
  NoDrop: '',
  Item1: 'crfb',
  Prob1: '1',
  Item2: 'crfc',
  Prob2: '1',
  Item3: 'crfs',
  Prob3: '1',
  Item4: 'crfh',
  Prob4: '1',
  Item5: 'crfv',
  Prob5: '1',
  Item6: 'crfu',
  Prob6: '1',
  Item7: 'crfp',
  Prob7: '1',
  Item8: '',
  Prob8: '',
  Item9: '',
  Prob9: '',
  Item10: '',
  Prob10: '',
  SumItems: '',
  TotalProb: '',
  DropChance: '',
  'Term': '0'
}